name: Update Version Footer

on:
  push:
    branches:
      - main
  schedule:
    - cron: '47 21 * * *'  # 21:47 UTC

permissions:
  contents: read

jobs:
  update-version:
    if: github.repository == 'JBChangelogs/JailbreakChangelogs'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Get commit info
        id: commit-info
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            # For scheduled runs, use current timestamp and latest commit hash
            echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
          else
            # For push events, use the pushed commit's info
            echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "timestamp=$(git log -1 --format=%ct)" >> $GITHUB_OUTPUT
          fi

      - name: Make API Request
        run: |
          response=$(curl -s -X POST \
            "${{ secrets.UPDATE_VERSION_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "{\"type\":\"website\",\"version\":\"${{ steps.commit-info.outputs.hash }}\",\"last_updated\":${{ steps.commit-info.outputs.timestamp }}}" \
            -w "\n%{http_code}")

          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "API Response Status: $status_code"
          echo "API Response Body: $body"

          if [ "$status_code" -ge 400 ]; then
            echo "Error: API request failed with status $status_code"
            exit 1
          fi
